<?php

namespace App\Enums;

enum PromotionRuleType: string
{
    case MINIMUM_CART_TOTAL = 'MINIMUM_CART_TOTAL';
    case REQUIRES_PRODUCT = 'REQUIRES_PRODUCT';
    case REQUIRES_PRODUCT_CATEGORY = 'REQUIRES_PRODUCT_CATEGORY';
    case REQUIRES_PRODUCT_QUANTITY = 'REQUIRES_PRODUCT_QUANTITY';
}